# # This is a basic workflow to help you get started with Actions

# name: Deploy

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [master]
#   pull_request:
#     branches: [master]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout source code
#         uses: actions/checkout@v2

#       - name: Install Dependencies
#         run: npm install

#       - name: Build
#         run: npm run build

#       - name: Prepare Dist
#         run: cp Procfile package.json .npmrc dist/

#       - name: Generate deployment package
#         run: cd dist && zip -r deploy.zip . -x '*.git*' && cp deploy.zip ../

#       - name: Deploy to EB
#         uses: einaregilsson/beanstalk-deploy@v18
#         with:
#           aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           application_name: theproart_api
#           environment_name: Theproartapi-env
#           region: ap-south-1
#           version_label: ver-${{ github.sha }}
#           deployment_package: deploy.zip
